export type OpenApiMcpClassification = 'included' | 'deferred' | 'excluded-protocol'

export const MCP_OPENAPI_OPERATION_CLASSIFICATIONS = {
  'GET /api/v1/projects/{name}/traffic/referral-assessment': 'included',

  'GET /api/v1/projects/{name}/sentiment/settings': 'included',
  'PUT /api/v1/projects/{name}/sentiment/settings': 'included',
  'GET /api/v1/projects/{name}/sentiment': 'included',
  'GET /api/v1/projects/{name}/sentiment/evidence': 'included',
  'GET /api/v1/projects/{name}/sentiment/compare': 'included',
  'GET /api/v1/projects/{name}/sentiment/backfill-preview': 'included',
  'POST /api/v1/projects/{name}/sentiment/backfills': 'included',
  'GET /api/v1/projects/{name}/sentiment/jobs': 'included',
  'GET /api/v1/projects/{name}/sentiment/jobs/{jobId}': 'included',

  'GET /api/v1/operations/logs': 'included',
  'GET /api/v1/openapi.json': 'excluded-protocol',
  // The browser launchpad needs create-only collision semantics. Agents already
  // have the included project upsert tool and do not need a second create path.
  'POST /api/v1/projects': 'deferred',
  'PUT /api/v1/projects/{name}': 'included',
  'GET /api/v1/projects': 'included',
  'GET /api/v1/projects/{name}': 'included',
  'DELETE /api/v1/projects/{name}': 'deferred',
  'GET /api/v1/projects/{name}/delete-preview': 'included',
  'POST /api/v1/projects/{name}/locations': 'deferred',
  'GET /api/v1/projects/{name}/locations': 'deferred',
  'DELETE /api/v1/projects/{name}/locations/{label}': 'deferred',
  'PUT /api/v1/projects/{name}/locations/default': 'deferred',
  'GET /api/v1/projects/{name}/export': 'included',
  // Bulk data attachments are unsuitable for an MCP context window. Agents
  // use the included paginated snapshots read instead.
  'GET /api/v1/projects/{name}/results/export': 'excluded-protocol',
  'GET /api/v1/projects/{name}/queries': 'included',
  'PUT /api/v1/projects/{name}/queries': 'included',
  'DELETE /api/v1/projects/{name}/queries': 'included',
  // By-id delete is a convenience for id-addressed clients (the dashboard,
  // which lists queries with their row ids). Agents work with query TEXT, so
  // the by-text bulk delete tool above already covers the agent workflow —
  // defer the by-id tool until an agent actually needs id-addressed deletes.
  'DELETE /api/v1/projects/{name}/queries/{id}': 'deferred',
  'POST /api/v1/projects/{name}/queries': 'included',
  'POST /api/v1/projects/{name}/queries/generate': 'included',
  'POST /api/v1/projects/{name}/queries/replace-preview': 'included',
  'GET /api/v1/projects/{name}/keywords': 'included',
  'PUT /api/v1/projects/{name}/keywords': 'included',
  'DELETE /api/v1/projects/{name}/keywords': 'included',
  'POST /api/v1/projects/{name}/keywords': 'included',
  'POST /api/v1/projects/{name}/keywords/generate': 'included',
  'GET /api/v1/projects/{name}/competitors': 'included',
  'GET /api/v1/projects/{name}/analytics/competitors': 'included',
  'PUT /api/v1/projects/{name}/competitors': 'deferred',
  'POST /api/v1/projects/{name}/competitors': 'included',
  'DELETE /api/v1/projects/{name}/competitors': 'included',
  'PUT /api/v1/projects/{name}/competitors/{domain}/aliases': 'included',
  // By-id delete is useful for UI clients that render competitor row ids.
  // Agents work with competitor domains, so the domain-based remove tool above
  // covers the MCP workflow without forcing agents to look up ids first.
  'DELETE /api/v1/projects/{name}/competitors/{id}': 'deferred',
  'POST /api/v1/projects/{name}/runs': 'included',
  'POST /api/v1/projects/{name}/measurement-discovery': 'included',
  'GET /api/v1/projects/{name}/measurement-plan': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/compile-preview': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/diff-preview': 'included',
  'PUT /api/v1/projects/{name}/measurement-plan': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/segments/{stableKey}/retire': 'included',
  'GET /api/v1/projects/{name}/measurement-plan/versions': 'included',
  'GET /api/v1/projects/{name}/measurement-plan/versions/{revision}': 'included',
  'GET /api/v1/projects/{name}/measurement-report': 'included',
  // Advanced Measurement v2 routes are fully exposed through the MCP setup
  // toolkit, so the OpenAPI coverage gate verifies their tool mappings.
  'GET /api/v1/projects/{name}/measurement-setup': 'included',
  'GET /api/v1/projects/{name}/measurement-plan/draft': 'included',
  'GET /api/v1/projects/{name}/measurement-plan/draft/targets': 'included',
  'GET /api/v1/projects/{name}/measurement-plan/draft/assignments': 'included',
  'GET /api/v1/projects/{name}/measurement-plan/draft/groups': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/create': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/import-sitemap': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/apply-sitemap-selection': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/upsert-target': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/rename-target': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/merge-targets': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/exclude-target': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/rebind-target': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/apply-assignments': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/preview-assignments': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/replace-assignments': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/apply-paired-assignments': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/remove-assignment': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/clear-assignments': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/classify-assignments': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/upsert-group': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/upsert-market': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/remove-group': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/preview-group-membership': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/apply-group-membership': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/upsert-competitor': 'included',
  // The dashboard uses the dedicated additive pin action; agents can inspect
  // the landscape and use the existing explicit draft action workflow.
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/pin-competitor': 'deferred',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/remove-competitor': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/compile-preview': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/diff-preview': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/publish': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/draft/actions/discard': 'included',
  'POST /api/v1/projects/{name}/measurement-plan/actions/deactivate': 'included',
  'GET /api/v1/projects/{name}/measurement-overview': 'included',
  'GET /api/v1/projects/{name}/visibility-report': 'included',
  'GET /api/v1/projects/{name}/query-tracking': 'included',
  'POST /api/v1/projects/{name}/query-tracking/preview': 'included',
  'POST /api/v1/projects/{name}/query-tracking/commit': 'included',
  'GET /api/v1/projects/{name}/measurement-property-evidence': 'included',
  'GET /api/v1/projects/{name}/measurement-portfolio-summary': 'included',
  'GET /api/v1/projects/{name}/measurement-property-questions': 'included',
  'GET /api/v1/projects/{name}/measurement-question-result': 'included',
  'GET /api/v1/projects/{name}/measurement-property-competitors': 'included',
  'GET /api/v1/projects/{name}/measurement-changes': 'included',
  'GET /api/v1/projects/{name}/measurement-data-quality': 'included',
  'GET /api/v1/projects/{name}/measurement-query-sets': 'included',
  'GET /api/v1/projects/{name}/measurement-query-sets/{setId}': 'included',
  'PUT /api/v1/projects/{name}/measurement-query-sets/{setId}': 'included',
  'DELETE /api/v1/projects/{name}/measurement-query-sets/{setId}': 'included',
  'GET /api/v1/projects/{name}/measurement-query-templates': 'included',
  'PUT /api/v1/projects/{name}/measurement-query-templates/{templateId}': 'included',
  'DELETE /api/v1/projects/{name}/measurement-query-templates/{templateId}': 'included',
  'POST /api/v1/projects/{name}/measurement-query-templates/{templateId}/apply': 'included',
  'POST /api/v1/projects/{name}/results/clear': 'included',
  'POST /api/v1/projects/{name}/research/runs': 'included',
  'POST /api/v1/projects/{name}/research/batches': 'included',
  'GET /api/v1/projects/{name}/research/runs': 'included',
  'GET /api/v1/projects/{name}/research/runs/{runId}': 'included',
  'GET /api/v1/projects/{name}/organic-evidence': 'included',
  'GET /api/v1/projects/{name}/runs': 'included',
  'GET /api/v1/projects/{name}/runs/latest': 'included',
  // The dashboard's run-admission notice, without the latest run's answers.
  // Agents read the same `admission` from canonry_runs_latest and
  // canonry_project_overview, so a third tool would only repeat it.
  'GET /api/v1/projects/{name}/run-admission': 'deferred',
  'GET /api/v1/runs': 'deferred',
  'POST /api/v1/runs': 'deferred',
  'GET /api/v1/runs/{id}': 'included',
  'POST /api/v1/runs/{id}/cancel': 'included',
  'POST /api/v1/runs/{id}/fill': 'included',
  'GET /api/v1/runs/{id}/completeness': 'included',
  'POST /api/v1/apply': 'included',
  'GET /api/v1/projects/{name}/history': 'included',
  'GET /api/v1/history': 'included',
  'GET /api/v1/projects/{name}/snapshots': 'included',
  'GET /api/v1/projects/{name}/timeline': 'included',
  'GET /api/v1/projects/{name}/analytics/metrics': 'included',
  'GET /api/v1/projects/{name}/analytics/gaps': 'deferred',
  'GET /api/v1/projects/{name}/analytics/sources': 'included',
  'GET /api/v1/projects/{name}/visibility-stats': 'included',
  'GET /api/v1/projects/{name}/visibility-compare': 'included',
  'GET /api/v1/projects/{name}/snapshots/diff': 'included',
  'GET /api/v1/settings': 'included',
  // MCP exposes only non-secret model/quota edits; credential fields remain operator-only.
  'PUT /api/v1/settings/providers/{name}': 'included',
  'PUT /api/v1/settings/google': 'deferred',
  'POST /api/v1/snapshot': 'included',
  'PUT /api/v1/settings/bing': 'deferred',
  'PUT /api/v1/settings/cdp': 'deferred',
  // API key management — deliberately not surfaced as MCP tools. Minting and
  // revoking bearer tokens is a privilege-granting / access-cutting operation
  // (gated by the keys.write scope), in the same sensitive class as the
  // settings credential mutations above. CLI + API only for now.
  // Key creation and revocation remain deliberately outside MCP. Safe
  // introspection is exposed so agents can see the credential boundary that
  // already governs this connection.
  'GET /api/v1/keys': 'deferred',
  'GET /api/v1/keys/self': 'included',
  'POST /api/v1/keys': 'deferred',
  'POST /api/v1/keys/{id}/revoke': 'deferred',
  // The sign-in surface is how a PERSON reaches the dashboard in a browser. An
  // agent already holds an API key, which is the credential meant for it, so
  // there is nothing here for an agent to sign in to.
  'GET /api/v1/auth/session': 'excluded-protocol',
  'POST /api/v1/auth/login': 'excluded-protocol',
  'POST /api/v1/auth/logout': 'excluded-protocol',
  'GET /api/v1/auth/sessions': 'excluded-protocol',
  'DELETE /api/v1/auth/sessions': 'excluded-protocol',
  // Creating and deleting accounts hands out (or cuts off) a way into this
  // install, which is the same privilege-granting class as minting a key.
  // Deliberately CLI + API only.
  'GET /api/v1/users': 'deferred',
  'POST /api/v1/users': 'deferred',
  'DELETE /api/v1/users/{name}': 'deferred',
  'PUT /api/v1/projects/{name}/schedule': 'included',
  'GET /api/v1/projects/{name}/schedules': 'included',
  'GET /api/v1/projects/{name}/schedule': 'included',
  'DELETE /api/v1/projects/{name}/schedule': 'included',
  'GET /api/v1/notifications/events': 'included',
  'POST /api/v1/projects/{name}/notifications': 'included',
  'GET /api/v1/projects/{name}/notifications': 'included',
  'DELETE /api/v1/projects/{name}/notifications/{id}': 'included',
  'POST /api/v1/projects/{name}/notifications/{id}/test': 'deferred',
  'GET /api/v1/telemetry': 'included',
  'PUT /api/v1/telemetry': 'included',
  // Dashboard-to-local-server observability protocol. It records no product
  // capability and is intentionally not an agent tool.
  'POST /api/v1/telemetry/onboarding': 'excluded-protocol',
  'POST /api/v1/telemetry/ui': 'excluded-protocol',
  'POST /api/v1/feedback': 'included',
  'GET /api/v1/screenshots/{snapshotId}': 'excluded-protocol',
  'GET /api/v1/cdp/status': 'deferred',
  'POST /api/v1/cdp/screenshot': 'deferred',
  'GET /api/v1/projects/{name}/runs/{runId}/browser-diff': 'deferred',
  'GET /api/v1/google/callback': 'excluded-protocol',
  'GET /api/v1/projects/{name}/google/callback': 'excluded-protocol',
  'POST /api/v1/google-marketing/callback/confirm/{confirmationId}': 'excluded-protocol',
  'GET /api/v1/projects/{name}/google/connections': 'included',
  'POST /api/v1/projects/{name}/google/connect': 'deferred',
  'DELETE /api/v1/projects/{name}/google/connections/{type}': 'deferred',
  'GET /api/v1/projects/{name}/google/properties': 'deferred',
  'PUT /api/v1/projects/{name}/google/connections/{type}/property': 'deferred',
  'PUT /api/v1/projects/{name}/google/connections/{type}/sitemap': 'deferred',
  'POST /api/v1/projects/{name}/google/gsc/sync': 'deferred',
  'GET /api/v1/projects/{name}/google/gsc/performance': 'included',
  'GET /api/v1/projects/{name}/google/gsc/performance/daily': 'included',
  'GET /api/v1/projects/{name}/google/gsc/top-pages': 'included',
  'GET /api/v1/projects/{name}/google/gsc/query-totals': 'included',
  'POST /api/v1/projects/{name}/google/gsc/inspect': 'deferred',
  'GET /api/v1/projects/{name}/google/gsc/inspections': 'included',
  'GET /api/v1/projects/{name}/google/gsc/deindexed': 'included',
  'GET /api/v1/projects/{name}/google/gsc/coverage': 'included',
  'GET /api/v1/projects/{name}/google/gsc/coverage/history': 'included',
  'GET /api/v1/projects/{name}/google/gsc/sitemaps': 'included',
  'POST /api/v1/projects/{name}/google/gsc/sitemaps/submit': 'included',
  'POST /api/v1/projects/{name}/google/gsc/discover-sitemaps': 'deferred',
  'POST /api/v1/projects/{name}/google/gsc/inspect-sitemap': 'deferred',
  'POST /api/v1/projects/{name}/google/indexing/request': 'deferred',
  'POST /api/v1/projects/{name}/gbp/locations/discover': 'included',
  'GET /api/v1/projects/{name}/gbp/accounts': 'included',
  'GET /api/v1/projects/{name}/gbp/locations': 'included',
  'PUT /api/v1/projects/{name}/gbp/locations/{locationName}/selection': 'included',
  'DELETE /api/v1/projects/{name}/gbp/connection': 'included',
  'POST /api/v1/projects/{name}/gbp/sync': 'included',
  // OpenAI ads: connect carries the raw SDK key (credential-bearing) and
  // disconnect destroys the stored credential — both stay off the MCP/agent
  // surface like the settings credential mutations. Reads + sync are tools.
  'POST /api/v1/projects/{name}/ads/connect': 'deferred',
  'DELETE /api/v1/projects/{name}/ads/connection': 'deferred',
  'GET /api/v1/projects/{name}/ads/status': 'included',
  'GET /api/v1/projects/{name}/ads/account': 'included',
  'GET /api/v1/projects/{name}/ads/geo/search': 'included',
  'GET /api/v1/projects/{name}/ads/conversions/pixels': 'included',
  'GET /api/v1/projects/{name}/ads/conversions/event-settings': 'included',
  'GET /api/v1/projects/{name}/ads/operations': 'included',
  'GET /api/v1/projects/{name}/ads/operations/{operationKey}': 'included',
  'POST /api/v1/projects/{name}/ads/operations/{operationKey}/reconcile': 'included',
  'POST /api/v1/projects/{name}/ads/operations/{operationKey}/resume-activation': 'included',
  // Approval and revoke remain human API/CLI surfaces. The agent receives only
  // the separately scoped, exact-grant execution operation.
  'POST /api/v1/projects/{name}/ads/activation-grants': 'deferred',
  'POST /api/v1/projects/{name}/ads/activation-grants/{grantId}/revoke': 'deferred',
  'POST /api/v1/projects/{name}/ads/files': 'included',
  'POST /api/v1/projects/{name}/ads/campaigns': 'included',
  'POST /api/v1/projects/{name}/ads/campaigns/{id}': 'included',
  'POST /api/v1/projects/{name}/ads/campaigns/{id}/pause': 'included',
  // Archive is irreversible. It stays a human API surface until it has been
  // exercised against a test advertiser account; agents get pause instead.
  'POST /api/v1/projects/{name}/ads/campaigns/{id}/archive': 'deferred',
  'POST /api/v1/projects/{name}/ads/campaigns/{id}/activate-tree': 'included',
  'POST /api/v1/projects/{name}/ads/ad-groups': 'included',
  'POST /api/v1/projects/{name}/ads/ad-groups/{id}': 'included',
  'POST /api/v1/projects/{name}/ads/ad-groups/{id}/pause': 'included',
  'POST /api/v1/projects/{name}/ads/ad-groups/{id}/archive': 'deferred',
  'POST /api/v1/projects/{name}/ads/ads': 'included',
  'POST /api/v1/projects/{name}/ads/ads/{id}': 'included',
  'POST /api/v1/projects/{name}/ads/ads/{id}/pause': 'included',
  'POST /api/v1/projects/{name}/ads/ads/{id}/archive': 'deferred',
  'POST /api/v1/projects/{name}/ads/sync': 'included',
  'GET /api/v1/projects/{name}/ads/campaigns': 'included',
  'GET /api/v1/projects/{name}/ads/insights': 'included',
  'GET /api/v1/projects/{name}/ads/summary': 'included',
  'GET /api/v1/projects/{name}/ads/delivery-diagnostics': 'included',
  'GET /api/v1/projects/{name}/ads/live-delivery': 'included',
  'GET /api/v1/projects/{name}/gbp/metrics': 'included',
  'GET /api/v1/projects/{name}/gbp/keywords': 'included',
  'GET /api/v1/projects/{name}/gbp/place-actions': 'included',
  'GET /api/v1/projects/{name}/gbp/lodging': 'included',
  'GET /api/v1/projects/{name}/gbp/attributes': 'included',
  'GET /api/v1/projects/{name}/gbp/places': 'included',
  'GET /api/v1/projects/{name}/gbp/reviews': 'included',
  'GET /api/v1/projects/{name}/gbp/summary': 'included',
  // Google Marketing is split into explicit Google Ads and GTM namespaces.
  // It is deliberately separate from `ads`, which means OpenAI / ChatGPT Ads.
  // OAuth hand-offs carry or destroy private credentials, while conversion
  // contracts are the operator's declared business semantics; keep those
  // mutation workflows on the human CLI/dashboard for v1. Provider reads,
  // bounded syncs, stored evidence, and deterministic integrity reads are
  // safe agent capabilities.
  'GET /api/v1/projects/{name}/google-ads/status': 'included',
  'GET /api/v1/projects/{name}/gtm/status': 'included',
  'POST /api/v1/projects/{name}/google-ads/oauth/connect': 'deferred',
  'POST /api/v1/projects/{name}/gtm/oauth/connect': 'deferred',
  'GET /api/v1/google-marketing/callback': 'excluded-protocol',
  'GET /api/v1/projects/{name}/google-ads/customers': 'included',
  'GET /api/v1/projects/{name}/gtm/accounts': 'included',
  'GET /api/v1/projects/{name}/gtm/accounts/{accountId}/containers': 'included',
  'GET /api/v1/projects/{name}/gtm/accounts/{accountId}/containers/{containerId}/workspaces': 'included',
  'PUT /api/v1/projects/{name}/google-ads/selection': 'deferred',
  'PUT /api/v1/projects/{name}/gtm/selection': 'deferred',
  'POST /api/v1/projects/{name}/google-ads/sync': 'included',
  'POST /api/v1/projects/{name}/gtm/sync': 'included',
  // Computed performance over the STORED snapshot. Quota-free and budget-free:
  // it never calls Google, unlike the live customers/sync reads above.
  'GET /api/v1/projects/{name}/conversion-tracking/options': 'included',
  'GET /api/v1/projects/{name}/google-ads/performance': 'included',
  'GET /api/v1/projects/{name}/google-ads/snapshots': 'included',
  'GET /api/v1/projects/{name}/google-ads/snapshots/{snapshotId}': 'included',
  'GET /api/v1/projects/{name}/gtm/snapshots': 'included',
  'GET /api/v1/projects/{name}/gtm/snapshots/{snapshotId}': 'included',
  'DELETE /api/v1/projects/{name}/google-ads/connection': 'deferred',
  'DELETE /api/v1/projects/{name}/gtm/connection': 'deferred',
  'GET /api/v1/projects/{name}/conversion-tracking/contracts': 'included',
  'POST /api/v1/projects/{name}/conversion-tracking/contracts': 'deferred',
  'GET /api/v1/projects/{name}/conversion-tracking/contracts/{contractId}': 'included',
  'PUT /api/v1/projects/{name}/conversion-tracking/contracts/{contractId}': 'deferred',
  'DELETE /api/v1/projects/{name}/conversion-tracking/contracts/{contractId}': 'deferred',
  'GET /api/v1/projects/{name}/conversion-tracking/contracts/{contractId}/integrity': 'included',
  'POST /api/v1/projects/{name}/bing/connect': 'deferred',
  'DELETE /api/v1/projects/{name}/bing/disconnect': 'deferred',
  'GET /api/v1/projects/{name}/bing/status': 'deferred',
  'GET /api/v1/projects/{name}/bing/sites': 'deferred',
  'POST /api/v1/projects/{name}/bing/set-site': 'deferred',
  'GET /api/v1/projects/{name}/bing/coverage': 'included',
  'GET /api/v1/projects/{name}/bing/coverage/history': 'deferred',
  'GET /api/v1/projects/{name}/bing/inspections': 'deferred',
  'POST /api/v1/projects/{name}/bing/inspect-url': 'deferred',
  'POST /api/v1/projects/{name}/bing/inspect-sitemap': 'deferred',
  'POST /api/v1/projects/{name}/bing/request-indexing': 'deferred',
  'GET /api/v1/projects/{name}/bing/performance': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/connect': 'deferred',
  'POST /api/v1/projects/{name}/traffic/connect/cloud-run': 'included',
  'POST /api/v1/projects/{name}/traffic/connect/wordpress': 'included',
  'POST /api/v1/projects/{name}/traffic/connect/vercel': 'included',
  // Cloudflare setup generates per-source secrets and installs them into
  // Worker secret bindings from the local Canonry credential store. Keep the
  // operation out of MCP so neither credentials nor deployment material can
  // enter an agent transcript; use the local `canonry traffic connect
  // cloudflare ...` CLI workflow instead.
  'POST /api/v1/projects/{name}/traffic/connect/cloudflare': 'deferred',
  // The ingest endpoint uses per-source HMAC auth, not the cnry_* bearer
  // an MCP agent would carry. Routing it through MCP would also be the
  // wrong shape — events are pushed by a customer-deployed Worker, not
  // by an AI agent. Exclude it from the MCP catalog.
  'POST /api/v1/projects/{name}/traffic/cloudflare/ingest': 'excluded-protocol',
  // Activating a staged Cloudflare transport is the human cutover point after
  // route inspection/deployment. Keep that safety acknowledgement in the
  // local CLI rather than making it agent-callable.
  'POST /api/v1/projects/{name}/traffic/sources/{id}/activate': 'excluded-protocol',
  'POST /api/v1/projects/{name}/traffic/sources/{id}/sync': 'included',
  'POST /api/v1/projects/{name}/traffic/sources/{id}/backfill': 'included',
  'POST /api/v1/projects/{name}/traffic/sources/{id}/reset': 'included',
  'GET /api/v1/projects/{name}/traffic/sources': 'included',
  'GET /api/v1/projects/{name}/traffic/status': 'included',
  'GET /api/v1/projects/{name}/traffic/analytics': 'included',
  'GET /api/v1/projects/{name}/traffic/sources/{id}': 'included',
  'GET /api/v1/projects/{name}/traffic/events': 'included',
  'DELETE /api/v1/projects/{name}/wordpress/disconnect': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/status': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/pages': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/page': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/pages': 'deferred',
  'PUT /api/v1/projects/{name}/wordpress/page': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/page/meta': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/pages/meta/bulk': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/schema': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/schema/manual': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/schema/deploy': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/schema/status': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/llms-txt': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/llms-txt/manual': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/audit': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/diff': 'deferred',
  'GET /api/v1/projects/{name}/wordpress/staging/status': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/staging/push': 'deferred',
  'POST /api/v1/projects/{name}/wordpress/onboard': 'deferred',
  'POST /api/v1/projects/{name}/ga/connect': 'deferred',
  'DELETE /api/v1/projects/{name}/ga/disconnect': 'deferred',
  'GET /api/v1/projects/{name}/ga/properties': 'included',
  'GET /api/v1/projects/{name}/ga/status': 'included',
  'GET /api/v1/projects/{name}/ga/measurement-analysis': 'included',
  'POST /api/v1/projects/{name}/ga/sync': 'deferred',
  'GET /api/v1/projects/{name}/ga/traffic': 'included',
  'GET /api/v1/projects/{name}/ga/ai-referral-history': 'included',
  'GET /api/v1/projects/{name}/ga/ai-referral-daily': 'included',
  'GET /api/v1/projects/{name}/ga/social-referral-history': 'included',
  'GET /api/v1/projects/{name}/ga/social-referral-trend': 'included',
  'GET /api/v1/projects/{name}/ga/attribution-trend': 'included',
  'GET /api/v1/projects/{name}/ga/session-history': 'included',
  'GET /api/v1/projects/{name}/ga/coverage': 'included',
  'GET /api/v1/projects/{name}/content/targets': 'included',
  'GET /api/v1/projects/{name}/content/sources': 'included',
  'GET /api/v1/projects/{name}/content/gaps': 'included',
  // Winnability gate surfaces — the deterministic classification map
  // (canonry_content_map) and the structured brief synthesizer
  // (canonry_content_brief). The brief is gated to ownable targets and
  // analyze-tier-cached, so Aero can act on it headless. The GET brief is a
  // cache-only read; the POST tool returns the cached brief on a hit, so a
  // separate read tool would be redundant — deferred like GET analysis.
  'GET /api/v1/projects/{name}/content/domain-classifications': 'included',
  'POST /api/v1/projects/{name}/content/recommendations/{targetRef}/brief': 'included',
  'GET /api/v1/projects/{name}/content/recommendations/{targetRef}/brief': 'deferred',
  // Persisted dismissals remain inspectable and reversible without Report.
  'GET /api/v1/projects/{name}/content/dismissals': 'included',
  'POST /api/v1/projects/{name}/content/dismissals': 'included',
  'DELETE /api/v1/projects/{name}/content/dismissals/{targetRef}': 'included',
  // Recommendation explanations remain deferred: adding a paid analysis
  // command needs its own CLI/MCP workflow and authority review. The cached
  // read stays API-only until that workflow is exposed.
  'GET /api/v1/projects/{name}/content/recommendations/{targetRef}/analysis': 'deferred',
  'POST /api/v1/projects/{name}/content/recommendations/{targetRef}/analyze': 'deferred',
  'GET /api/v1/projects/{name}/insights': 'included',
  'GET /api/v1/projects/{name}/insights/{id}': 'included',
  'POST /api/v1/projects/{name}/insights/{id}/dismiss': 'included',
  'GET /api/v1/projects/{name}/health/latest': 'included',
  'GET /api/v1/projects/{name}/health/history': 'included',
  'GET /api/v1/projects/{name}/citations/visibility': 'included',
  'GET /api/v1/projects/{name}/overview': 'included',
  'GET /api/v1/projects/{name}/search': 'included',
  'GET /api/v1/doctor': 'included',
  'GET /api/v1/projects/{name}/doctor': 'included',
  'GET /api/v1/backlinks/status': 'deferred',
  'POST /api/v1/backlinks/install': 'deferred',
  'POST /api/v1/backlinks/syncs': 'deferred',
  'GET /api/v1/backlinks/syncs': 'deferred',
  'GET /api/v1/backlinks/syncs/latest': 'deferred',
  'GET /api/v1/backlinks/releases': 'deferred',
  'GET /api/v1/backlinks/latest-release': 'included',
  'DELETE /api/v1/backlinks/cache/{release}': 'deferred',
  'POST /api/v1/projects/{name}/backlinks/extract': 'deferred',
  'GET /api/v1/projects/{name}/backlinks/summary': 'deferred',
  'GET /api/v1/projects/{name}/backlinks/domains': 'included',
  'GET /api/v1/projects/{name}/backlinks/sources': 'included',
  'GET /api/v1/projects/{name}/backlinks/history': 'deferred',
  'GET /api/v1/projects/{name}/agent/conversations': 'included',
  'POST /api/v1/projects/{name}/agent/conversations': 'included',
  'GET /api/v1/projects/{name}/agent/conversations/{id}': 'included',
  'POST /api/v1/projects/{name}/agent/conversations/{id}/resume': 'included',
  'DELETE /api/v1/projects/{name}/agent/conversations/{id}': 'included',
  'GET /api/v1/projects/{name}/agent/transcript': 'deferred',
  'DELETE /api/v1/projects/{name}/agent/transcript': 'included',
  'GET /api/v1/projects/{name}/agent/memory': 'included',
  'PUT /api/v1/projects/{name}/agent/memory': 'included',
  'DELETE /api/v1/projects/{name}/agent/memory': 'included',
  'GET /api/v1/projects/{name}/agent/providers': 'deferred',
  'POST /api/v1/projects/{name}/agent/prompt': 'excluded-protocol',
  'POST /api/v1/projects/{name}/discover/run': 'included',
  'GET /api/v1/projects/{name}/discover/sessions': 'included',
  'GET /api/v1/projects/{name}/discover/sessions/{id}': 'included',
  'GET /api/v1/projects/{name}/discover/sessions/{id}/harvest': 'included',
  'GET /api/v1/projects/{name}/discover/sessions/{id}/promote': 'included',
  'POST /api/v1/projects/{name}/discover/sessions/{id}/promote': 'included',
  'GET /api/v1/projects/{name}/technical-aeo': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/pages': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/trend': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/crawl': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/subgraph': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/path': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/changes': 'included',
  // The interactive map projection is dashboard transport; agents already
  // have the cursor-paged inventory and bounded page-neighbor reads.
  'GET /api/v1/projects/{name}/technical-aeo/graph': 'deferred',
  'GET /api/v1/projects/{name}/technical-aeo/crawl/pages': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/crawl/pages/audit': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/structure': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/internal-links': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/internal-links/neighbors': 'included',
  'GET /api/v1/projects/{name}/technical-aeo/dead-links': 'included',
  // Scan history exists so the dashboard's run picker can label a legacy
  // score-only scan. Agents address a scan by `runId` on the reads above and
  // already get run provenance from the trend and changes tools, so this is
  // deferred until an agent workflow actually needs to enumerate scans.
  'GET /api/v1/projects/{name}/technical-aeo/runs': 'deferred',
  // Raw crawl-attempt counters exist for transient onboarding progress. Agents
  // use run_get plus the canonical crawl reads once evidence is published.
  'GET /api/v1/projects/{name}/technical-aeo/runs/{runId}/progress': 'deferred',
  // This is a transient browser-polling projection with no durable final
  // findings. Agents use the canonical Page Health reads after publication.
  'GET /api/v1/projects/{name}/technical-aeo/runs/{runId}/page-health-preview': 'excluded-protocol',
  'POST /api/v1/projects/{name}/technical-aeo/runs': 'included',
} as const satisfies Record<string, OpenApiMcpClassification>
