// Generated by scripts/sync-val-town-skills.mjs. Do not edit.
// Source of truth: skills/<name>/ at the repository root.

import type { SkillDocument } from '../skill-types.js'

import { part as aeroSkillPart0 } from './aero-skill.0.js'
import { part as aeroReferencesAeoDiscoveryPart0 } from './aero-references-aeo-discovery.0.js'
import { part as aeroReferencesAgentOperationsPart0 } from './aero-references-agent-operations.0.js'
import { part as aeroReferencesMemoryPatternsPart0 } from './aero-references-memory-patterns.0.js'
import { part as aeroReferencesOrchestrationPart0 } from './aero-references-orchestration.0.js'
import { part as aeroReferencesPortfolioAnalysisPart0 } from './aero-references-portfolio-analysis.0.js'
import { part as aeroReferencesRegressionPlaybookPart0 } from './aero-references-regression-playbook.0.js'
import { part as aeroReferencesReportingPart0 } from './aero-references-reporting.0.js'
import { part as aeroReferencesSiteHealthPart0 } from './aero-references-site-health.0.js'
import { part as aeroReferencesWordpressElementorMcpPart0 } from './aero-references-wordpress-elementor-mcp.0.js'
import { part as aeroSoulPart0 } from './aero-soul.0.js'
import { part as canonrySkillPart0 } from './canonry-skill.0.js'
import { part as canonryReferencesAeoAnalysisPart0 } from './canonry-references-aeo-analysis.0.js'
import { part as canonryReferencesCanonryCliPart0 } from './canonry-references-canonry-cli.0.js'
import { part as canonryReferencesCanonryCliPart1 } from './canonry-references-canonry-cli.1.js'
import { part as canonryReferencesCanonryCliPart2 } from './canonry-references-canonry-cli.2.js'
import { part as canonryReferencesGoogleBusinessProfilePart0 } from './canonry-references-google-business-profile.0.js'
import { part as canonryReferencesGoogleMarketingPart0 } from './canonry-references-google-marketing.0.js'
import { part as canonryReferencesIndexingPart0 } from './canonry-references-indexing.0.js'
import { part as canonryReferencesServerSideTrafficPart0 } from './canonry-references-server-side-traffic.0.js'
import { part as canonryReferencesWordpressIntegrationPart0 } from './canonry-references-wordpress-integration.0.js'

export const SKILL_DOCUMENTS: readonly SkillDocument[] = [
  {
    uri: "canonry-skill://aero/SKILL.md",
    skill: "aero",
    path: "SKILL.md",
    title: "aero skill",
    description: "Diagnose AEO regressions and interpret Canonry AI visibility, Advanced multi-property portfolios, and Site Health evidence. Use when a mention or citation coverage number moved and needs explaining, when comparing Properties or markets, diagnosing crawl or page findings, preparing a client report or month-over-month comparison, or analyzing a completed `cnry` sweep or site audit. Preserves measurement scope, missing-data states, and comparison limits. Use the canonry skill for setup and operations.",
    entryPoint: true,
    characters: 17157,
    content: aeroSkillPart0,
  },
  {
    uri: "canonry-skill://aero/references/aeo-discovery.md",
    skill: "aero",
    path: "references/aeo-discovery.md",
    title: "AEO Discovery (Tracked-Basket Expansion)",
    description: "How to operate the tracked-basket discovery pipeline. Read when an operator asks to expand a project's basket, audit its competitive surface, or you wake unprompted on `aeo-discover-probe.completed`.",
    entryPoint: false,
    characters: 13316,
    content: aeroReferencesAeoDiscoveryPart0,
  },
  {
    uri: "canonry-skill://aero/references/agent-operations.md",
    skill: "aero",
    path: "references/agent-operations.md",
    title: "Canonry Operations Guide v1",
    description: "Shared Canonry vocabulary, evidence scope, comparison rules, and authority boundaries. Read when interpreting unfamiliar data or checking an operation.",
    entryPoint: false,
    characters: 14120,
    content: aeroReferencesAgentOperationsPart0,
  },
  {
    uri: "canonry-skill://aero/references/memory-patterns.md",
    skill: "aero",
    path: "references/memory-patterns.md",
    title: "Memory Patterns",
    description: "When to remember vs. re-query — project state lives in canonry, only durable user-scoped facts go in Aero memory. Read when unsure whether to call canonry_memory_set or look up.",
    entryPoint: false,
    characters: 4458,
    content: aeroReferencesMemoryPatternsPart0,
  },
  {
    uri: "canonry-skill://aero/references/orchestration.md",
    skill: "aero",
    path: "references/orchestration.md",
    title: "Orchestration Workflows",
    description: "Workflow recipes — baseline, regression response, weekly review, content gap analysis. Read when planning a multi-step task or recurring review.",
    entryPoint: false,
    characters: 7780,
    content: aeroReferencesOrchestrationPart0,
  },
  {
    uri: "canonry-skill://aero/references/portfolio-analysis.md",
    skill: "aero",
    path: "references/portfolio-analysis.md",
    title: "Portfolio analysis",
    description: "Interpret Simple and Advanced portfolios, compare Properties and markets, trace answer evidence, and qualify missing or incompatible measurements.",
    entryPoint: false,
    characters: 9883,
    content: aeroReferencesPortfolioAnalysisPart0,
  },
  {
    uri: "canonry-skill://aero/references/regression-playbook.md",
    skill: "aero",
    path: "references/regression-playbook.md",
    title: "Regression Playbook",
    description: "Detection → triage → diagnosis → response for lost mentions (primary) and lost citations (secondary). Read when investigating why a query lost a mention or a citation.",
    entryPoint: false,
    characters: 8306,
    content: aeroReferencesRegressionPlaybookPart0,
  },
  {
    uri: "canonry-skill://aero/references/reporting.md",
    skill: "aero",
    path: "references/reporting.md",
    title: "Reporting Templates",
    description: "Weekly and monthly report templates with metric tables, regression/gain sections, and recommended-actions structure. Read when asked to produce a client-facing summary.",
    entryPoint: false,
    characters: 9973,
    content: aeroReferencesReportingPart0,
  },
  {
    uri: "canonry-skill://aero/references/site-health.md",
    skill: "aero",
    path: "references/site-health.md",
    title: "Site Health diagnosis",
    description: "Diagnose Site Health scores, page findings, crawl coverage, internal links, and scan changes while preserving run provenance and incomplete-data limits.",
    entryPoint: false,
    characters: 6191,
    content: aeroReferencesSiteHealthPart0,
  },
  {
    uri: "canonry-skill://aero/references/wordpress-elementor-mcp.md",
    skill: "aero",
    path: "references/wordpress-elementor-mcp.md",
    title: "Elementor + WordPress MCP Development Guide",
    description: "WordPress + Elementor MCP integration guide — prerequisites, auth, widget manipulation. Read only when the task involves editing WordPress/Elementor pages.",
    entryPoint: false,
    characters: 8449,
    content: aeroReferencesWordpressElementorMcpPart0,
  },
  {
    uri: "canonry-skill://aero/soul.md",
    skill: "aero",
    path: "soul.md",
    title: "Who You Are",
    description: "Aero's persona, values, and voice — context-agnostic identity that applies whether Aero runs as the built-in agent or wraps around an external agent shell.",
    entryPoint: false,
    characters: 3173,
    content: aeroSoulPart0,
  },
  {
    uri: "canonry-skill://canonry/SKILL.md",
    skill: "canonry",
    path: "SKILL.md",
    title: "canonry skill",
    description: "Navigate Canonry through connected MCP tools or the `cnry` CLI to inspect evidence, diagnose changes, plan measurement, review integrations, and report results. Use this optional host-native skill for CLI workflows and detailed references; connected MCP users can operate through canonry_help without installing a local runtime or skill.",
    entryPoint: true,
    characters: 14338,
    content: canonrySkillPart0,
  },
  {
    uri: "canonry-skill://canonry/references/aeo-analysis.md",
    skill: "canonry",
    path: "references/aeo-analysis.md",
    title: "AEO Analysis: Interpreting Canonry Results",
    description: "canonry skill reference: references/aeo-analysis.md",
    entryPoint: false,
    characters: 17325,
    content: canonryReferencesAeoAnalysisPart0,
  },
  {
    uri: "canonry-skill://canonry/references/canonry-cli.md",
    skill: "canonry",
    path: "references/canonry-cli.md",
    title: "Canonry CLI Reference",
    description: "canonry skill reference: references/canonry-cli.md",
    entryPoint: false,
    characters: 137900,
    content: [canonryReferencesCanonryCliPart0, canonryReferencesCanonryCliPart1, canonryReferencesCanonryCliPart2].join(''),
  },
  {
    uri: "canonry-skill://canonry/references/google-business-profile.md",
    skill: "canonry",
    path: "references/google-business-profile.md",
    title: "Google Business Profile Integration",
    description: "canonry skill reference: references/google-business-profile.md",
    entryPoint: false,
    characters: 35976,
    content: canonryReferencesGoogleBusinessProfilePart0,
  },
  {
    uri: "canonry-skill://canonry/references/google-marketing.md",
    skill: "canonry",
    path: "references/google-marketing.md",
    title: "Google Ads and Google Tag Manager",
    description: "canonry skill reference: references/google-marketing.md",
    entryPoint: false,
    characters: 6311,
    content: canonryReferencesGoogleMarketingPart0,
  },
  {
    uri: "canonry-skill://canonry/references/indexing.md",
    skill: "canonry",
    path: "references/indexing.md",
    title: "Indexing Workflows for AEO",
    description: "canonry skill reference: references/indexing.md",
    entryPoint: false,
    characters: 6542,
    content: canonryReferencesIndexingPart0,
  },
  {
    uri: "canonry-skill://canonry/references/server-side-traffic.md",
    skill: "canonry",
    path: "references/server-side-traffic.md",
    title: "Server-side traffic (AI Visibility — Server-Side)",
    description: "canonry skill reference: references/server-side-traffic.md",
    entryPoint: false,
    characters: 56052,
    content: canonryReferencesServerSideTrafficPart0,
  },
  {
    uri: "canonry-skill://canonry/references/wordpress-integration.md",
    skill: "canonry",
    path: "references/wordpress-integration.md",
    title: "WordPress Integration",
    description: "canonry skill reference: references/wordpress-integration.md",
    entryPoint: false,
    characters: 2258,
    content: canonryReferencesWordpressIntegrationPart0,
  },
]
